spring:
  application:
    name: product

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8070/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true

server:
  port: 8084

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
  config: classpath:logback-spring.xml
  file:
    path: /var/log/spring # Match Promtail path