apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: pes1ug21cs120ashritbharadwaj/bookapp:1.1
    ports:
      - containerPort: 80
