apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapp-deploy
  annotations:
    kubernetes.io/change-cause: "deploying v1"
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app:  bookapp-service
  replicas: 4
  template:
    metadata:
      labels:
        app:  bookapp-service
    spec:
      containers:
      - name:  bookapp-service
        image: pes1ug21cs120ashritbharadwaj/bookapp:1.1
        ports:
        - name: "app-port"
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bookapp-svc
spec:
  type: NodePort
  selector:
    app: bookapp-service
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001