apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapp-deploy
  annotations:
    kubernetes.io/change-cause: "deploying v4"
spec:
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app:  bookapp-service
  replicas: 4
  template:
    metadata:
      labels:
        app:  bookapp-service
    spec:
      containers:
      - name:  bookapp-service
        image: pes1ug21cs120ashritbharadwaj/bookapp:1.4
        ports:
        - name: "app-port"
          containerPort: 8080