apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapp-deploy
  namespace: dev
  annotations:
    kubernetes.io/change-cause: "deploying v3"
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "100%"
      maxUnavailable: "25%"
  selector:
    matchLabels:
      app:  bookapp-service
  replicas: 4
  template:
    metadata:
      labels:
        app:  bookapp-service
    spec:
      containers:
      - name:  bookapp-service
        image: pes1ug21cs120ashritbharadwaj/bookapp:1.3
        ports:
        - name: "app-port"
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bookapp-svc
spec:
  type: NodePort
  selector:
    app: bookapp-service
  ports:
  - port: 8080 #port that we want to expose for pod
    targetPort: 8080 #port inside container
    nodePort: 30001
