apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-initdb-config
data:
  init-mongo.js: |
    db = db.getSiblingDB('product-service');
    db.createCollection('product');
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mongo
  labels:
    app: docker-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-mongo
  template:
    metadata:
      labels:
        app: docker-mongo
    spec:
      volumes:
        - name: mongo-initdb-vol
          configMap:
            name: mongo-initdb-config
      containers:
        - name: docker-mongo
          image: mongo:7.0.5
          env:
            - name: MONGO_INITDB_DATABASE
              value: product-service
          volumeMounts:
            - name: mongo-initdb-vol
              mountPath: /docker-entrypoint-initdb.d
---
apiVersion: v1
kind: Service
metadata:
    name: docker-mongo
    labels:
        app: docker-mongo
spec:
    selector:
        app: docker-mongo
    type: NodePort
    ports:
        - port: 27017
          targetPort: 27017
          nodePort: 30017