apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS `order-service`;
    USE `order-service`;
    CREATE TABLE IF NOT EXISTS `order` (
        order_id BIGINT AUTO_INCREMENT PRIMARY KEY,
        product_id VARCHAR(255) NOT NULL,
        quantity INT NOT NULL,
        status VARCHAR(255) NOT NULL,
        order_date TIMESTAMP NOT NULL,
        user_email VARCHAR(255) NOT NULL 
    );
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mysql
  labels:
    app: docker-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-mysql
  template:
    metadata:
      labels:
        app: docker-mysql
    spec:
      volumes:
        - name: mysql-initdb-vol
          configMap:
            name: mysql-initdb-config
      containers:
        - name: docker-mysql
          image: mysql:8.3.0
          env:
            - name: MYSQL_DATABASE
              value: order-service
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_ROOT_HOST
              value: '%'
          volumeMounts:
            - name: mysql-initdb-vol
              mountPath: /docker-entrypoint-initdb.d
---
apiVersion: v1
kind: Service
metadata:
    name: docker-mysql
    labels:
        app: docker-mysql
spec:
    selector:
        app: docker-mysql
    type: NodePort
    ports:
        - port: 3306
          targetPort: 3306
          nodePort: 30006